
[client]
	hide_indicator = false
	force_indicator_rendering = true
	#Range: 0.0 ~ 1.0
	font_size = 1.0
	#Range: 0 ~ 1024
	render_distance = 16
	change_color_when_crit = false
	disable_bigger_font_size_when_crit = false
	show_floating_point = true

	[client.color]

		[client.color.in_fire_damage]
			#Range: 0 ~ 255
			red = 255
			#Range: 0 ~ 255
			green = 150
			#Range: 0 ~ 255
			blue = 0

		[client.color.lightning_bolt_damage]
			#Range: 0 ~ 255
			red = 255
			#Range: 0 ~ 255
			green = 255
			#Range: 0 ~ 255
			blue = 255

		[client.color.on_fire_damage]
			#Range: 0 ~ 255
			red = 255
			#Range: 0 ~ 255
			green = 150
			#Range: 0 ~ 255
			blue = 0

		[client.color.lava_damage]
			#Range: 0 ~ 255
			red = 255
			#Range: 0 ~ 255
			green = 150
			#Range: 0 ~ 255
			blue = 0

		[client.color.hot_floor_damage]
			#Range: 0 ~ 255
			red = 255
			#Range: 0 ~ 255
			green = 150
			#Range: 0 ~ 255
			blue = 0

		[client.color.in_wall_damage]
			#Range: 0 ~ 255
			red = 43
			#Range: 0 ~ 255
			green = 43
			#Range: 0 ~ 255
			blue = 43

		[client.color.cramming_damage]
			#Range: 0 ~ 255
			red = 43
			#Range: 0 ~ 255
			green = 43
			#Range: 0 ~ 255
			blue = 43

		[client.color.drown_damage]
			#Range: 0 ~ 255
			red = 0
			#Range: 0 ~ 255
			green = 125
			#Range: 0 ~ 255
			blue = 255

		[client.color.starve_damage]
			#Range: 0 ~ 255
			red = 255
			#Range: 0 ~ 255
			green = 0
			#Range: 0 ~ 255
			blue = 0

		[client.color.cactus_damage]
			#Range: 0 ~ 255
			red = 255
			#Range: 0 ~ 255
			green = 255
			#Range: 0 ~ 255
			blue = 255

		[client.color.fall_damage]
			#Range: 0 ~ 255
			red = 255
			#Range: 0 ~ 255
			green = 255
			#Range: 0 ~ 255
			blue = 255

		[client.color.fly_into_wall_damage]
			#Range: 0 ~ 255
			red = 255
			#Range: 0 ~ 255
			green = 255
			#Range: 0 ~ 255
			blue = 255

		[client.color.out_of_world_damage]
			#Range: 0 ~ 255
			red = 43
			#Range: 0 ~ 255
			green = 43
			#Range: 0 ~ 255
			blue = 43

		[client.color.generic_damage]
			#Range: 0 ~ 255
			red = 255
			#Range: 0 ~ 255
			green = 255
			#Range: 0 ~ 255
			blue = 255

		[client.color.magic_damage]
			#Range: 0 ~ 255
			red = 255
			#Range: 0 ~ 255
			green = 0
			#Range: 0 ~ 255
			blue = 255

		[client.color.wither_damage]
			#Range: 0 ~ 255
			red = 43
			#Range: 0 ~ 255
			green = 43
			#Range: 0 ~ 255
			blue = 43

		[client.color.anvil_damage]
			#Range: 0 ~ 255
			red = 255
			#Range: 0 ~ 255
			green = 255
			#Range: 0 ~ 255
			blue = 255

		[client.color.falling_block_damage]
			#Range: 0 ~ 255
			red = 255
			#Range: 0 ~ 255
			green = 255
			#Range: 0 ~ 255
			blue = 255

		[client.color.dragon_breath_damage]
			#Range: 0 ~ 255
			red = 255
			#Range: 0 ~ 255
			green = 255
			#Range: 0 ~ 255
			blue = 255

		[client.color.dry_out_damage]
			#Range: 0 ~ 255
			red = 255
			#Range: 0 ~ 255
			green = 255
			#Range: 0 ~ 255
			blue = 255

		[client.color.sweet_berry_bush_damage]
			#Range: 0 ~ 255
			red = 255
			#Range: 0 ~ 255
			green = 255
			#Range: 0 ~ 255
			blue = 255

		[client.color.freeze_damage]
			#Range: 0 ~ 255
			red = 0
			#Range: 0 ~ 255
			green = 255
			#Range: 0 ~ 255
			blue = 255

		[client.color.falling_stalactite_damage]
			#Range: 0 ~ 255
			red = 255
			#Range: 0 ~ 255
			green = 255
			#Range: 0 ~ 255
			blue = 255

		[client.color.stalagmite_damage]
			#Range: 0 ~ 255
			red = 255
			#Range: 0 ~ 255
			green = 255
			#Range: 0 ~ 255
			blue = 255

		[client.color.critical]
			#Range: 0 ~ 255
			red = 255
			#Range: 0 ~ 255
			green = 255
			#Range: 0 ~ 255
			blue = 255

		[client.color.heal]
			#Range: 0 ~ 255
			red = 0
			#Range: 0 ~ 255
			green = 255
			#Range: 0 ~ 255
			blue = 0

