
["Abomination Turn"]
	#Infected Animals being turned into abominations
	"Turned Into An Abomination" = true

["Instant Infection For The Player"]
	#a chance for the player to instantly be converted into a fallen when he gets hit by a cursed mob, Heavily WIP
	"Instant Infection" = false

["Wave Enable"]
	#If Waves are false or True.
	Wave = true

["Soul Gains"]
	"Soul Gains" = 1.0

