
[VanillaTweaks]

	#New items, blocks VanillaTweaks adds.
	[VanillaTweaks.content]
		#Want to showcase your treasure but item frame doesn't satisfy you?
		enablePedestal = true
		#Want block forms of flint, charcoal and sugar?
		enableStorageBlocks = true
		#Do you want a portable crafting table?
		enablePad = false
		#Want to identity slime chunks in-game?
		enableSlimeBucket = false
		#Want a less effective but throwable TNT?
		enableDynamite = true
		#Cooldown for the dynamite in ticks
		#Range: > 0
		dynamiteCooldown = 80
		#Explosion power for dynamite. TNT has 4, Ender Crystal has 6
		#Range: 0 ~ 10
		dynamiteExplosionPower = 1
		#Want a food which can be obtained with eggs and heals 2.5 hunger?
		enableFriedEgg = false

	#Do you want enchantments?
	[VanillaTweaks.enchanting]
		#Want to smelt things when you mine them?
		enableBlazing = false
		#Want to jump more than a block high with an enchantment?
		enableHops = false
		#Want more speed with an enchantment?
		enableNimble = false
		#Don't want the zombies stealing your items when you are mining?
		enableSiphon = false
		#Want all the experience in the nearby area?
		enableVeteran = false
		#Want more health with an enchant?
		enableVigor = false
		#Don't want to aim but love shooting arrows?
		enableHoming = false
		#Want blazing enchantment to only appear in loot?
		blazingTreasureOnly = false
		#Want Hops enchantment to only appear in loot?
		hopsTreasureOnly = false
		#Want Nimble enchantment to only appear in loot?
		nimbleTreasureOnly = false
		#Want Siphon enchantment to only appear in loot?
		siphonTreasureOnly = false
		#Want Veteran enchantment to only appear in loot?
		veteranTreasureOnly = false
		#Want Vigor enchantment to only appear in loot?
		vigorTreasureOnly = false
		#Want Homing enchantment to only appear in loot?
		homingTreasureOnly = false

	#Mob Drops
	[VanillaTweaks.loot]
		#Do you want bat to drop leather when killed by a player?
		#Range: 0.0 ~ 10.0
		batLeatherDropChance = 1.0
		#Does a nametag drop when named mob dies?
		namedMobsDropNameTag = true

	#Modification of vanilla_recipes recipes and addition of new recipes regarding vanilla_recipes
	[VanillaTweaks.crafting]
		#Wanna craft multiple chests at one go?
		betterChest = false
		#Tired of not having a nametag?
		nametag = false
		#Have wool but need string?
		string = false
		#Want an easier way to craft repeater?
		betterRepeater = false
		#Wanna easier recipe for trapped chest?
		betterTrappedChestRecipe = false

	#Tweaks
	[VanillaTweaks.tweaks]
		#Want the fire arrows to set fire on block it landed?
		arrowsSetBlockOnFire = false
		#Want to shear nametag of named entities?
		shearOffNameTag = false
		#Want baby zombies to burn by the light of the day?
		babyZombieBurnInDaylight = false
		#Want creeper's to burn in daylight?
		creeperBurnInDaylight = false
		#Want TNT to ignite when next to lava or magma block?
		tntIgnition = false
		#Want hoe to act like a sickle?
		hoeActsAsSickle = false
		#Want the ability to move spawners with silk touch?
		enableSilkSpawner = false
		#Want an way to swap armor with armor stand?
		enableArmorStandSwapping = false
		#Want to see the no of bees or the honey level of an beehive?
		enableBeehiveTooltips = false
		#Want to shift click item frame to rotate in the reverse direction?
		itemFrameRotateBackwards = false

	#Dynamic changes in the world
	[VanillaTweaks.world]
		#Don't want that that pesky lava pockets in nether to kill you?
		disableLavaPocketGen = false
		#Is realistic predator/prey relationships activated?
		realisticRelationship = false
		#Want seeds to auto-plant themselves when broken?
		selfPlanting = false
		#List of item ID's to blacklist for self planting
		selfPlantingBlacklist = []
		#The number of ticks to wait to check whether a plant can be planted
		#Range: 20 ~ 6000
		selfPlantingInterval = 100

