
["Skill Points"]
	#Range: 1 ~ 1000
	"Maximum skill points" = 100
	#Range: > 0
	"First skill point cost" = 15
	#Range: > 0
	"Last skill point cost" = 1400
	#You can set cost for each skill point instead
	"Use skill points costs array" = true
	#This list's size must be equal to maximum skill points.
	"Levelup costs" = [7, 7, 16, 16, 27, 27, 40, 40, 55, 55, 72, 72, 91, 91, 112, 112, 135, 135, 160, 160, 187, 187, 216, 216, 247, 247, 280, 280, 315, 315, 352, 352, 394, 394, 441, 441, 493, 493, 550, 550, 612, 612, 679, 679, 751, 751, 828, 828, 910, 910, 997, 997, 1089, 1089, 1186, 1186, 1288, 1288, 1395, 1395, 1507, 1507, 1628, 1628, 1758, 1758, 1897, 1897, 2045, 2045, 2202, 2202, 2368, 2368, 2543, 2543, 2727, 2727, 2920, 2920, 3122, 3122, 3333, 3333, 3553, 3553, 3782, 3782, 4020, 4020, 4267, 4267, 4523, 4523, 4788, 4788, 5062, 5062, 5345, 5345]
	#Disabling this will remove chat messages when you gain a skill point.
	"Show chat messages" = true
	#Warning: If you disable this make sure you make alternative way of getting skill points.
	"Enable exprerience exchange for skill points" = true

[Gems]
	#Range: 0.0 ~ 1.0
	"Base drop chance" = 0.0

[Equipment]
	#Range: 0 ~ 4
	"Default Helmets Sockets" = 0
	#Range: 0 ~ 4
	"Default Chestplates Sockets" = 0
	#Range: 0 ~ 4
	"Default Leggings Sockets" = 0
	#Range: 0 ~ 4
	"Default Boots Sockets" = 0
	#Range: 0 ~ 4
	"Default Weapons Sockets" = 0
	#Range: 0 ~ 4
	"Default Shields Sockets" = 0
	#Range: 0 ~ 4
	"Default Rings Sockets" = 0
	#Range: 0 ~ 4
	"Default Necklaces Sockets" = 0
	#You can remove sockets from items here
	#Example: Blacklisting specific items: ["minecraft:diamond_hoe", "minecraft:golden_hoe"]
	#Example: Blacklisting whole mod: ["<mod_id>:*"]
	#Example: Blacklisting all items: ["*:*"]
	"IDs of items that shouldn't have sockets" = []

#You can force items from other mods into equipmentType categories here
["Amnesia Scroll"]
	#How much levels (percentage) player lose using amnesia scroll
	#Range: 0.0 ~ 1.0
	"Amnesia scroll penalty" = 0.2
	"Drop amnesia scrolls from the Ender Dragon" = false

[Experience]
	#Range: 0.0 ~ 1.0
	"Grindstone experience multiplier" = 0.0

[Mixtures]
	#Range: 0.0 ~ 2.0
	"Effects duration multiplier" = 1.0
	#Range: 0.0 ~ 2.0
	"Effects strength multiplier" = 1.0

