
[Boiler]
	#The water capacity of the boiler. The hot water capacity is 2x this.
	#Range: < 1073741823
	boilerWaterCapacity = 2000
	#How much water the boiler converts into hot water each tick whilst running.
	#Range: > 1
	boilerHeatingRate = 1

[Turbine]
	#The max speed (mb/t consumption) the turbine can reach.
	#Range: > 1
	maxTurbineSpeed = 200
	#How much FE the turbine makes for every mb of water it consumes.
	#Range: > 1
	turbineFERatio = 4
	#How long the turbine takes to spin up from still to max speed, in seconds.
	#Minimum speed gain is 1 per tick / 20 per second!
	#Range: > 0
	turbineSpinupTime = 60
	#How much water the turbine can hold.
	#Range: > 1000
	turbineWaterCapacity = 10000
	#How much power the turbine can hold.
	#Range: > 1000
	turbinePowerCapacity = 10000

[MultiblockTurbine]
	#The max speed (mb/t consumption) the multiblock turbine can reach.
	#Range: > 1
	multiblockTurbineMaxSpeed = 1000
	#How much FE the turbine makes for every mb of water it consumes.
	#Range: > 1
	multiblockTurbineFeRatio = 6
	#How long the turbine takes to spin up from still to max speed, in seconds.
	#Minimum speed gain is 1 per tick / 20 per second!
	#Range: > 0
	multiblockTurbineSpinupTime = 100
	#How much water the turbine can hold.
	#Range: > 1000
	multiblockTurbineWaterCapacity = 50000
	#How much power the turbine can hold.
	#Range: > 1000
	multiblockTurbinePowerCapacity = 50000

[LightningGenerator]
	#The power consumption of the lightning generator.
	#Range: > 1
	lightningGeneratorConsumption = 1000
	#The lightning generator's power capacity.
	#Range: > 1
	lightningGeneratorCapacity = 100000

[LightningDynamo]
	#How much power each dynamo produces per connected lightning generator.
	#Range: > 1
	lightningDynamoProduction = 10000
	#How much power the lightning dynamo can store.
	#Range: > 1
	lightningDynamoCapacity = 10000000
	#How many lightning generators a single dynamo can connect to.
	#Range: 1 ~ 4
	lightningDynamoMaxGenerators = 4

[Washer]
	#How much power the washer can hold.
	#Range: > 1000
	washerPowerCapacity = 256000
	#How much power is consumed per cobblestone 'washed'.
	#Range: > 1
	washerPowerConsumption = 82000
	#How much water the washer can hold.
	#Range: > 1000
	washerWaterCapacity = 10000
	#How much water is consumed per cobblestone 'washed'.
	#Range: > 1
	washerWaterConsumption = 6000
	#How many ticks it takes to 'wash' a single block of cobblestone.
	#Range: > 1
	washerProcessTime = 1100

[Tank]
	#How much fluid the tank can store.
	#Range: > 1000
	fluidTankCapacity = 100000

[Pump]
	#How much fluid the pump can store.
	#Range: > 1000
	pumpFluidCapacity = 10000
	#The search range for the pump. Higher values perform worse.
	#Range: 1 ~ 512
	pumpRange = 32
	#Whether or not the fluid pump should drain water. Pumps infinitely if disabled.
	pumpDrainsWater = false
	#The power consumption of the fluid pump per block pumped. Must be lower than the capacity!
	#Range: > 0
	pumpPowerConsumption = 500
	#The power capacity of the fluid pump.
	#Range: > 1000
	pumpPowerCapacity = 10000
	#The power conversion per tick of burn time the inserted fuel has. The resulting power is rounded to the nearest whole number!
	#Range: 0.001 ~ 1.7976931348623157E308
	pumpPowerConversion = 1.0
	#How frequently the pump can operate. 1 = every tick!
	#Range: > 1
	pumpOperationTime = 5

[Pipe]
	#How often pipes can pull from inventories. 1 = every tick!
	#Range: > 1
	fluidPipeFrequency = 3
	#How much fluid a pipe will pull with each operation.
	#Range: > 1
	fluidPipeRate = 1000

