# Use Cloth Config mod for the descriptions.
---
modules:
  farmersdelight: true
  bee: true
  vacuum: true
  ritual: true
  food: true
treeGrowingSpeed: 5
fruitDropMode:
  singleplayer: Independent
  multiplayer: OneByOne
fruitTreeLifespan:
  min: 999995
  max: 999999
appleSaplingFromHeroOfTheVillage: false
villageAppleTreeWorldGen: true
hornHarvestingInstrument: minecraft:sing_goat_horn
wanderingTraderSapling: true
beeNaturalHealingInterval: 600
mutagenRecipe: true
redloveFruitUse: true
dragonBreath:
  fixExploit: true
  dispenserCollecting: true
leavesUsInPeaceIncompatibilityNotified: false
geneticsDifficulty: Normal
mutationRate:
  RC: 0.12
  FT1: 0.32
  FT2: 0.24
  FC: 0.4
imperfectMutagenChance: 0.15
mutagenMutationRate: 0.8
