
[General]
	#Print all found mob IDS to the console, will cause spam
	printIDs = false
	#Protects all mobs from fire
	protectAllMobs = false
	#Protects these mods from fire (any mobs with these namespaces)
	mods = ["iceandfire"]
	#Protects these mobs from fire (any mobs with these ids (namespace:name))
	mobs = ["minecraft:zombie", "minecraft:drowned", "minecraft:zombie_villager", "minecraft:husk", "zombie_more:crawler_zombie", "zombie_more:tank_zombie", "zombie_more:boomer_zombie", "undead_revamp2:bomber", "undead_revamp2:thespitter", "undead_revamp2:theheavy", "undead_revamp2:thehunter"]

