#Credits for LootTables method - Fungal Infection:Spore
#item|chance to drop(1-100)|minimum amount|maximum amount.Only values above 0 will be taken in consideration.
"Flesh Human Loot" = []
"Flesh Villager Loot" = []
"Flesh Vindicator Loot" = []
"Flesh Pillager Loot" = []
"Flesh Infector Loot" = []
"Flesh Pig Loot" = []
"Flesh Cow Loot" = []
"Flesh Sheep Loot" = []
"Flesh Dog Loot" = []
"Flesh Mutant Loot" = []
"Flesh Brute I Loot" = []
"Flesh Human Head Loot" = []
"Flesh Piece Loot" = []
"Flesh Hunter I Loot" = []
"Flesh Hunter II Loot" = []
"Flesh Hysterizer Loot" = []
"Flesh Suffer Loot" = []
"Flesh Boomer Loot" = []
"Flesh Howler Loot" = []
"Flesh Unseen Loot" = []
"Flesh Community Loot" = []
"Flesh Justice Loot" = []
"Flesh Cocoon Loot" = []
"Flesh Servant Loot" = []
"Flesh Incubator Embryo Loot" = []
"Flesh Incubator Enlightenment Loot" = []

