#Chooses the time (in ticks) Wandering Traders in Wandering Shops wait for before restocking their inventories
#Range: > 0
restocking_time = 24000
#Specify the damage a Wandering Fighter inflicts on its target. The below number is a multiplier on their base stat.
#Range: 0.0 ~ 1.7976931348623157E308
fighter_damage = 3.5
#Specify the health boost a Wandering Trader gets after being hurt
#Range: 0.0 ~ 1.7976931348623157E308
fighter_health = 12.5
#Specify the health boost a Trader Llama gets after being hurt or after it's Wandering Trader is hurt
#The below number is a multiplier on their base stat.
#Range: 0.0 ~ 1.7976931348623157E308
llama_health = 12.5
#Specifies the amount of time that needs to pass between Llama Spit attacks. The time is in ticks
#Range: > 1
llama_spit_interval = 10
#Specify the speed boost that the wandering trader gets after being enraged. The number below is multiplied by their current stat.
#Range: 0.0 ~ 1.7976931348623157E308
trader_speed_boost = 0.5
#Whether the Wandering Trader will drop its shop contents on death
trader_drop_shop_contents = false

